apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: block-pvc-scanner
  namespace: kube-monitoring
  labels:
    app: pvc-exporter
    com: block-pvc-scanner
spec:
  selector:
    matchLabels:
      com: block-pvc-scanner
      app: pvc-exporter
  template:
    metadata:
      labels:
        com: block-pvc-scanner
        app: pvc-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8848"
        prometheus.io/targets: "collector-kubernetes"
    spec:
      containers:
      - name: block-pvc-scanner
        image: keppel.eu-de-1.cloud.sap/ccloud/block-pvc-scanner:87da20c0
        ports:
        - containerPort: 8848
          name: metrics
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: root-path
          mountPath: /host
          readOnly: true
      volumes:
      - name: root-path
        hostPath:
          path: /
